@startuml
Customer as User
ApiServer as Api

User -- (Movie Search)
User -- (Paging Movie Search)

'<<include>>
(Movie Search) ..> (Result Toast Msg)
(Paging Movie Search) ..> (Result Toast Msg)

'<<extend>>
(Movie Search) <.. (Network Notification)
(Paging Movie Search) <.. (Fail Toast Msg)

(Movie Search) <|--- (Local Movie Search)
(Movie Search) <|--- (Remote Movie Search)

note right of Api : <<Actor>>
(Movie Search) ---- Api
(Paging Movie Search) ---- Api

@enduml